#端口，项目上下文根
server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encding: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/

#热部署生效
devtools:
  restart:
    enabled: true

photo:
  path: ./src/main/resources/static/images/